name: Publish to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

  release:
    types: [created]

jobs:
  build_publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with: access_token:${{github.token}}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: lint
        run: npx eslint src --max-warnings 0

      - name: test
        run: npm run test -- --coverage

      - name: build storybook
        run: npm run build-storybook

      - name: Build ui package
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Publish package to NPM
        if: ${{ github.event_name == 'push'}}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN}}

      - name: Grab version
        id: version
        run: echo "::set-output name=version::$(jq -r '.version' /package.json)"
